# Exported from Render on 2024-04-23T15:24:01Z
services:
- type: web
  name: explorer-garlic-trove-q6wn
  runtime: python
  repo: https://github.com/JoyDenise/Mavin_Sales_Challenge
  plan: free
  envVars:
  - key: PYTHON_VERSION
    sync: false
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn --chdir src app:server
version: "1"
